### ISSUE TITLE
default_qdisc=fq ?

### ISSUE THREAD

**Issue by peterbaumert** [freifunkMUC/ffmuc-salt-public#76]
https://github.com/freifunkMUC/ffmuc-salt-public/blob/c34399b6c53071cbb4f3f41138d6848d99fd21ae/sysctl/global.sls#L111

Shouldn't you also add

```
net.core.default_qdisc:
  sysctl.present:
    - value: fq
    - config: /etc/sysctl.d/10-bbr-congestion.conf
 ```
